name: daily_done
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  get_it: ^8.0.3
  equatable: ^2.0.7
  dartz: ^0.10.1
  flutter_bloc: ^9.1.0
  flutter_screenutil: ^5.9.3
  path_provider: ^2.1.1
#  flutter_local_notifications: ^15.1.0
#  timezone: ^0.9.2
  fl_chart: ^0.64.0
  get: ^4.7.2
  sqflite: ^2.4.0
  path: ^1.9.0
  bloc: ^9.0.0
  meta: ^1.11.0
dev_dependencies:

  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.3"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/img.png"
  min_sdk_android: 21

flutter_lints: ^4.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/




